name: Mentorr - Build & Deploy

on:
  push:
    branches: ["main"]

jobs:
  angular:
    name: Setup do Frontend
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.17.0]
    steps:
      # {1}
      - name: Validando código
        uses: actions/checkout@v3
      # {2}
      - name: Validando cache do Node.js
        uses: actions/setup-node@v3
        with:
          node-version: $
          cache: "npm"
          cache-dependency-path: ./web/package-lock.json
      # {3}
      - name: Instalando dependências
        run: |
          cd web
          npm ci
      # {4}
      - name: Executando lint
        run: npm run lint
      # {5}
      - name: Executando build
        run: npm run build:prod
      # {6}
      - name: Atualizando gh-pages
        run: npm run deploy

  # maven:
  #   name: Setup do Backend
  #   runs-on: ubuntu-latest
  #   steps:
  #     # {1}
  #     - name: Validando código
  #       uses: actions/checkout@v4
  #     # {2}
  #     - name: Configurando JDK 11
  #       uses: actions/setup-java@v4
  #       with:
  #         java-version: "11"
  #         distribution: "temurin"
  #         cache: maven
  #     # {3}
  #     - name: Executando Build
  #       run: mvn -B package --file pom.xml
